general {
    ignore_empty_input = true
}

background {
    monitor =
    color = rgb(191d24)
}

input-field {
    monitor =
    size = 260, 50
    outline_thickness = 3
    inner_color = rgba(1c1c1ee6)
    outer_color = rgba(3a3a3cff)
    check_color = rgba(7b8494ff)
    fail_color = rgba(ff453aff)
    capslock_color = rgba(ffcc00ff)
    font_color = rgba(e5e5eaff)
    font_family = FiraCode Nerd Font Mono
    fail_text = <i>$FAIL ($ATTEMPTS)</i>
    fade_on_empty = false
    placeholder_text =
    position = 0, 0
    halign = center
    valign = center
}
