-- Mouse actions while holding SUPER (disabled; mango had these commented).
-- hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), { mouse = true })
-- hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), { mouse = true })
